# Run: docker-compose -p api-course-docs up

services: # Defines a list of services that will be created and managed by Docker Compose.
  api-server: # Defines the api-server service.
    build: # Specifies build options for the api-server service.
      context: ./server # Sets the build context to the ./server directory.
      dockerfile: Dockerfile # Tells Docker to use the Dockerfile located in the ./server directory to build the image.
    ports: # Exposes ports to the host machine.
      - '8080:8080' # Maps port 8080 on the host to port 8080 in the container.
    volumes: # Mounts directories from the host into the container.
      - ./server:/app # Mounts the ./server directory on the host to the /app directory in the container.
    depends_on: # Specifies that this service depends on other services.
      - pos-db # The api-server service depends on the pos-db service.

  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - '8000:8000'
    environment:
      - PORT=8000
      - SWAGGER_FILE=/openapi/openapi.original.yml
    volumes:
      - ./openapi:/openapi

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - '5500:5500'
    environment:
      - PORT=5500
      - SWAGGER_JSON=/openapi/openapi.original.yml
    volumes:
      - ./openapi:/openapi

  pos-db: # Defines the pos-db service.
    image: mongo # Specifies the Docker image to use, which is mongo (MongoDB).
    ports: # Exposes ports to the host machine.
      - '27017:27017' # Maps port 27017 on the host to port 27017 in the container, which is the default port for MongoDB.
