services:
  api-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '80:8080'
    volumes:
      - ./server:/server
    depends_on:
      - pos-db
    user: 'node'
    mem_limit: 2g # Set memory limit to 2GB for api-server

  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - '8080:8080'
    environment:
      - SWAGGER_FILE=/openapi/openapi.yml
    volumes:
      - ./openapi:/openapi
    mem_limit: 2g

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - '5500:8080'
    environment:
      - SWAGGER_JSON=/openapi/openapi.original.yml
    volumes:
      - ./openapi:/openapi
    mem_limit: 2g

  pos-db:
    image: mongo
    ports:
      - '27017:27017'
    mem_limit: 2g
