version: '3.8'

services:
  api-server:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/api-documentation-course
    ports:
      - '80:8080'
    depends_on:
      - pos-db

  pos-db:
    image: mongo
    ports:
      - '27017:27017'

  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - '8080:8080'
    volumes:
      - ../openapi:/openapi

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - '5500:8080'
    volumes:
      - ../openapi:/openapi
